services:
  vectordb:
    build:
      context: ./vector_db
    container_name: floatchat_vectordb
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./vector_db/.env
    volumes:
      - ./vector_db/floatchat/vectordb/chroma_vector_db:/app/chroma_vector_db
    networks:
      - floatchat_net

  ingestion:
    build:
      context: ./ingestion
    container_name: floatchat_ingestion
    ports:
      - "8100:8100"
    restart: always
    env_file:
      - ./ingestion/.env
    volumes:
      - ./ingestion/source_files:/app/source_files
      - ./ingestion/parquet:/app/parquet
    depends_on:
      - vectordb
    networks:
      - floatchat_net


networks:
  floatchat_net:
    driver: bridge
